config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat.save
  end

  def edit
  end

  def update
    @flat.update(params[:flat])
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.length %>) </h1>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-10 col-md-4 col-xs-offset-1">
        <div class="card">
          <h2><i class="fas fa-building"></i><%= flat.name %> </h2>
          <p><i class="fas fa-map-marker-alt"></i><%= flat.address %></p>
          <p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
          <p><i class="fas fa-user"></i><%= flat.number_of_guests %> </p>
          <p><% flat.rating.times do %>
            <i class="fas fa-star"></i>
            <% end %>
            <%= flat.rating %>
          </p>
          <%= link_to "More info", flat_path(flat), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-md-3 col-xs-offset-1">
      <div class="card">
        <h2><i class="fas fa-building"></i><%= @flat.name %> </h2>
        <p><i class="fas fa-map-marker-alt"></i><%= @flat.address %> </p>
        <p><i class="fas fa-euro-sign"></i><%= @flat.price_per_night %></p>
        <p><i class="fas fa-user"></i><%= @flat.number_of_guests %></p>
        <p>
          <% @flat.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <%= @flat.rating %>
        </p>
        <%= link_to "Back to flats", flats_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ml-2" %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>